#!/bin/bash

MKTEMP="mktemp"
DEBUG=0
PIPENV="pipenv"
TESTMOVIE1="Fight.Club.1995.BluRay.720p.x264.DTS-SPARKS.mkv"
TESTMOVIE2="Forrest.Gump.1994.DVDRip.DivX-CHD.avi"
EXPECTED1="Fight Club (1999)"
EXPECTED2="Forrest Gump (1994) (comment)"  # Used to test manual naming

################################################################################
# Functions
################################################################################

die() {
	echo "FATAL: $1"
	abort
}

debug() {
	[ "$DEBUG" -ne 0 ] && echo "DEBUG: $1"
}

verify_command() {
	CMD="$1"
	command -v "$CMD" > /dev/null || die "Required command not found: $CMD"
}

cleanup() {
	if [ -z "$DEBUG" ] || [ $DEBUG -eq 0 ]; then
		[ -d "$TEMPDIR" ] && [ ! -z "$TEMPDIR" ] && rm -Rf "$TEMPDIR"
	else
		debug "Not deleting $TEMPDIR so you can debug. Run this command \
			afterwards:"
		debug "rm -Rf \"$TEMPDIR\""
	fi
}

abort() {
	cleanup
	exit 1
}


################################################################################
# Main code starts here
################################################################################

# In debug mode, also make script under test verbose
if [ -z "$DEBUG" ] || [ $DEBUG -eq 0 ]; then
	VERBOSE=""
else
	VERBOSE="-v"
fi

# To ensure temporary directory is removed even in case of CTRL-C
trap abort SIGINT SIGTERM SIGKILL

# Make sure all the required commands are there
verify_command "$PIPENV"
verify_command "$MKTEMP"

# Create a temporary working directory, it is where the virtualenv will be
# created.
TEMPDIR=$($MKTEMP -d /tmp/imdbtag.XXXXXXXXXX)
debug "TEMPDIR: $TEMPDIR"
[ -d "$TEMPDIR" ] || die "Could not create temporary directory."


################################################################################
# 1) Test set-up
################################################################################

MOVIEFILE1="$TEMPDIR"/"$TESTMOVIE1"
MOVIEFILE2="$TEMPDIR"/"$TESTMOVIE2"
IMDBTAG="imdbtag"
touch "$MOVIEFILE1"
touch "$MOVIEFILE2"

#echo "Creating virtual environment"
#"$PIPENV" install 2>&1 | sed 's/^/- /' \
#	|| die "Could not create virtual environment"

echo "Installing imdbtag"
"$PIPENV" run python setup.py install 2>&1 | sed 's/^/- /' \
	|| die "Could not install application"


################################################################################
# 2) Execute
################################################################################

echo "Executing $IMDBTAG in offline mode"
	
CMD="$PIPENV run $IMDBTAG $VERBOSE -os $MOVIEFILE1"
debug "Command: '$CMD'"
$CMD | sed 's/^/- /' \
	|| die "Error running $CMD"

CMD="$PIPENV run $IMDBTAG $VERBOSE $MOVIEFILE2"
debug "Command: '$CMD'"
echo -e "\n\nForrest Gump (1994) (comment)\n\n" | $CMD | sed 's/^/- /' \
	|| die "Error running $CMD with input"


################################################################################
# 3) Verify
################################################################################

FAIL=0

if [ ! -d "$TEMPDIR"/"$EXPECTED1" ]; then
	echo "Test 1 failed: Directory \"$TEMPDIR/$EXPECTED1\" not found"
	FAIL=1
else
	echo "Test 1 PASSED!"
fi

if [ ! -d "$TEMPDIR"/"$EXPECTED2" ]; then
	echo "Test 2 failed: Directory \"$TEMPDIR/$EXPECTED2\" not found"
	FAIL=1
else
	echo "Test 2 PASSED!"
fi

if [ $FAIL -eq 1 ]; then
	echo "Some tests failed!"
	abort
fi

cleanup
